import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { HashRouter, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { getAnswers, getConfig, metrics, saveConfig, subscribe, sync, type Answer } from './data';
import './styles.css';

const nav=[['/','Dashboard'],['/answers','All Answers'],['/analytics','Analytics'],['/calendar','Calendar'],['/revision','Revision Hub'],['/pyq','PYQ Tracker'],['/goals','Goals'],['/learnings','Learnings'],['/flashcards','Flashcards'],['/settings','Settings']] as const;
function Layout(){const location=useLocation();const title=nav.find(x=>x[0]===location.pathname)?.[1]||'AnswerOS';return <div className="shell"><aside><div className="brand"><div className="brandMark">A</div><div><b>AnswerOS</b><small>UPSC Answer Intelligence</small></div></div><nav>{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}</nav><div className="sideFoot">Single source of truth<br/><span>Google Sheet → AnswerOS</span></div></aside><main><header><div><small>ANSWEROS</small><h1>{title}</h1></div><SyncButton/></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/settings" element={<Settings/>}/><Route path="/answers" element={<List title="All Answers"/>}/><Route path="/analytics" element={<List title="Analytics"/>}/><Route path="/calendar" element={<List title="Consistency Calendar"/>}/><Route path="/revision" element={<List title="Revision Hub"/>}/><Route path="/pyq" element={<List title="PYQ Tracker"/>}/><Route path="/goals" element={<List title="Goals"/>}/><Route path="/learnings" element={<List title="Learnings"/>}/><Route path="/flashcards" element={<List title="Flashcards"/>}/></Routes></main></div>}
function SyncButton(){const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');async function go(){setBusy(true);setMsg('');try{const n=await sync();setMsg(`${n} rows synced`)}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy(false)}}return <div className="sync"><button onClick={go} disabled={busy}>{busy?'Syncing…':'↻ Refresh from Sheet'}</button>{msg&&<span>{msg}</span>}</div>}
function Dashboard(){const [answers,setAnswers]=useState(getAnswers());useEffect(()=>subscribe(()=>setAnswers(getAnswers())),[]);const m=useMemo(()=>metrics(answers),[answers]);return <><section className="stats">{[['Answers',m.total],['Average',m.avg===null?'—':m.avg.toFixed(1)+'/10'],['Best',m.best===null?'—':m.best.toFixed(1)+'/10'],['Worst',m.worst===null?'—':m.worst.toFixed(1)+'/10'],['Demand',m.avgDemand===null?'—':Math.round(m.avgDemand)+'%']].map(([k,v])=><div className="stat" key={String(k)}><small>{k}</small><strong>{v}</strong></div>)}</section><div className="grid"><Card title="Paper Distribution"><div className="bars">{m.papers.map(([p,n])=><div className="barRow" key={p}><b>{p}</b><div><i style={{width:`${Math.min(100,n/Math.max(1,m.total)*100)}%`}}/></div><span>{n}</span></div>)}</div></Card><Card title="Recent Answers"><AnswerList answers={answers.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6)}/></Card><Card title="Performance Signal"><div className="signal"><strong>{m.avg===null?'No scored answers yet':m.avg>=6?'Strong base':'Build analytical depth'}</strong><p>{m.avg===null?'Sync evaluated answers to begin analytics.':`Your current average is ${m.avg.toFixed(1)}/10 across ${answers.length} answers.`}</p></div></Card><Card title="Data Health"><p className="muted">All dashboard metrics are derived from the canonical AnswerOS dataset.</p><p className="muted">Missing dates or demand values are shown as unavailable rather than fabricated.</p></Card></div></>}
function AnswerList({answers}:{answers:Answer[]}){return <div>{answers.map(a=><div className="answer" key={a.id}><div><b>{a.question||a.subtopic||'Untitled answer'}</b><small>{a.date||'Date unavailable'} · {a.paper} · {a.subject||'—'}</small></div><strong>{a.score10===null?'—':a.score10.toFixed(1)+'/10'}</strong></div>)}</div>}
function Card({title,children}:{title:string,children:ReactNode}){return <section className="card"><h2>{title}</h2>{children}</section>}
function List({title}:{title:string}){const [answers,setAnswers]=useState(getAnswers());useEffect(()=>subscribe(()=>setAnswers(getAnswers())),[]);return <Card title={`${title} · ${answers.length} synced answers`}><AnswerList answers={answers.slice().sort((a,b)=>b.date.localeCompare(a.date))}/></Card>}
function Settings(){const [c,setC]=useState(getConfig());const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);function update(k:keyof typeof c,v:string|boolean|number){const next={...c,[k]:v};setC(next);saveConfig(next)}async function doSync(){setBusy(true);try{const n=await sync();setMsg(`Successfully synced ${n} answers.`)}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy(false)}}return <div className="settings"><Card title="Google Sheet Sync"><p className="muted">The Google Sheet remains the source of truth. React reads the same v2 local store as the legacy pages.</p><label>Web App URL<input value={c.syncUrl} onChange={e=>update('syncUrl',e.target.value)} placeholder="https://script.google.com/macros/s/.../exec"/></label><label>Sync token<input value={c.syncToken} onChange={e=>update('syncToken',e.target.value)} placeholder="Optional"/></label><div className="row"><button onClick={doSync} disabled={busy}>{busy?'Syncing…':'Sync Now'}</button><button className="secondary" onClick={()=>setMsg('Settings saved locally.')}>Save</button></div>{msg&&<p className="notice">{msg}</p>}</Card><Card title="Migration status"><p>React + TypeScript foundation is active in <code>/app</code>.</p><p className="muted">The legacy HTML pages remain untouched as a fallback while the new app is migrated.</p></Card></div>}
export default function App(){return <HashRouter><Layout/></HashRouter>}
