import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { HashRouter, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { getAnswers, getConfig, metrics, saveConfig, subscribe, sync, type Answer } from './data';
import './styles.css';

const nav=[['/','Dashboard'],['/answers','All Answers'],['/analytics','Analytics'],['/calendar','Calendar'],['/revision','Revision Hub'],['/pyq','PYQ Tracker'],['/goals','Goals'],['/learnings','Learnings'],['/flashcards','Flashcards'],['/settings','Settings']] as const;
function useLiveAnswers(){const [answers,setAnswers]=useState(getAnswers());useEffect(()=>subscribe(()=>setAnswers(getAnswers())),[]);return answers}
function Layout(){const location=useLocation();const title=nav.find(x=>x[0]===location.pathname)?.[1]||'AnswerOS';return <div className="shell"><aside><div className="brand"><div className="brandMark">A</div><div><b>AnswerOS</b><small>UPSC Answer Intelligence</small></div></div><nav>{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}</nav><div className="sideFoot">Single source of truth<br/><span>Google Sheet → AnswerOS</span></div></aside><main><header><div><small>ANSWEROS</small><h1>{title}</h1></div><SyncButton/></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/answers" element={<Answers/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/calendar" element={<Calendar/>}/><Route path="/revision" element={<Revision/>}/><Route path="/pyq" element={<Pyq/>}/><Route path="/goals" element={<Goals/>}/><Route path="/learnings" element={<Learnings/>}/><Route path="/flashcards" element={<Flashcards/>}/><Route path="/settings" element={<Settings/>}/></Routes></main></div>}
function SyncButton(){const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');async function go(){setBusy(true);setMsg('');try{const n=await sync();setMsg(`${n} answers synced`)}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy(false)}}return <div className="sync"><button onClick={go} disabled={busy}>{busy?'Syncing…':'↻ Refresh from Sheet'}</button>{msg&&<span>{msg}</span>}</div>}
function Card({title,children}:{title:string,children:ReactNode}){return <section className="card"><h2>{title}</h2>{children}</section>}
function Stat({label,value}:{label:string,value:string|number}){return <div className="stat"><small>{label}</small><strong>{value}</strong></div>}
function AnswerList({answers,limit}:{answers:Answer[],limit?:number}){const list=answers.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,limit);return <div>{list.map(a=><div className="answer" key={a.id}><div><b>{a.question||a.subtopic||a.theme||'Untitled answer'}</b><small>{a.date||'Date unavailable'} · {a.paper} · {a.subject||'—'}{a.directive?` · ${a.directive}`:''}</small></div><strong>{a.score10===null?'—':a.score10.toFixed(1)+'/10'}</strong></div>)}</div>}
function Dashboard(){const answers=useLiveAnswers();const m=useMemo(()=>metrics(answers),[answers]);return <><section className="stats"><Stat label="Answers" value={m.total}/><Stat label="Average" value={m.avg===null?'—':m.avg.toFixed(1)+'/10'}/><Stat label="Best" value={m.best===null?'—':m.best.toFixed(1)+'/10'}/><Stat label="Worst" value={m.worst===null?'—':m.worst.toFixed(1)+'/10'}/><Stat label="Demand" value={m.avgDemand===null?'—':Math.round(m.avgDemand)+'%'}/></section><div className="grid"><Card title="Paper Distribution"><Distribution answers={answers}/></Card><Card title="Recent Answers"><AnswerList answers={answers} limit={7}/></Card><Card title="Performance Signal"><div className="signal"><strong>{m.avg===null?'No scored answers yet':m.avg>=6?'Strong base':m.avg>=5?'Developing':'Build analytical depth'}</strong><p>{m.avg===null?'Sync evaluated answers to begin analytics.':`Current average: ${m.avg.toFixed(1)}/10 across ${answers.length} answers.`}</p></div></Card><Card title="Data Health"><p className="muted">Live React pages consume the canonical v2 dataset. Missing dates and demand values remain unavailable rather than fabricated.</p></Card></div></>}
function Distribution({answers}:{answers:Answer[]}){const rows=Object.entries(answers.reduce<Record<string,number>>((m,a)=>(m[a.paper]=(m[a.paper]||0)+1,m),{})).sort((a,b)=>b[1]-a[1]);return <div className="bars">{rows.length?rows.map(([p,n])=><div className="barRow" key={p}><b>{p}</b><div><i style={{width:`${Math.min(100,n/Math.max(1,answers.length)*100)}%`}}/></div><span>{n}</span></div>):<p className="muted">No synced answers.</p>}</div>}
function Answers(){const answers=useLiveAnswers();const [q,setQ]=useState('');const [paper,setPaper]=useState('All');const [sort,setSort]=useState('date');const filtered=answers.filter(a=>(paper==='All'||a.paper===paper)&&(`${a.question} ${a.subject} ${a.theme} ${a.subtopic}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='score'?(b.score10??-1)-(a.score10??-1):(b.date||'').localeCompare(a.date||''));return <><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search answers, themes, subjects…"/><select value={paper} onChange={e=>setPaper(e.target.value)}><option>All</option>{[...new Set(answers.map(a=>a.paper))].filter(Boolean).map(p=><option key={p}>{p}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Newest</option><option value="score">Highest score</option></select></div><Card title={`${filtered.length} of ${answers.length} answers`}><AnswerList answers={filtered}/></Card></>}
function Analytics(){const answers=useLiveAnswers();const m=metrics(answers);const subjects=groupAverage(answers,a=>a.subject||'Unclassified');const directives=groupAverage(answers,a=>a.directive||'Unspecified');const gaps=countBy(answers,a=>a.gapCategory||'No gap recorded');return <div className="grid"><Card title="Performance"><section className="stats compact"><Stat label="Scored" value={answers.filter(a=>a.score10!==null).length}/><Stat label="Average" value={m.avg===null?'—':m.avg.toFixed(1)}/><Stat label="Demand" value={m.avgDemand===null?'—':Math.round(m.avgDemand)+'%'}/></section><Bars rows={subjects} suffix="/10"/></Card><Card title="Directive Performance"><Bars rows={directives} suffix="/10"/></Card><Card title="Recurring Gaps"><Bars rows={gaps.map(([k,n])=>[k,n])} suffix=""/></Card><Card title="Score Trend"><Trend answers={answers}/></Card></div>}
function groupAverage(answers:Answer[],key:(a:Answer)=>string):[string,number][]{const map:Record<string,number[]>={};answers.forEach(a=>{if(a.score10!==null){const k=key(a);(map[k]??=[]).push(a.score10)}});return Object.entries(map).map(([k,v])=>[k,Math.round(v.reduce((x,y)=>x+y,0)/v.length*10)/10]).sort((a,b)=>b[1]-a[1]).slice(0,10)}
function countBy(answers:Answer[],key:(a:Answer)=>string):[string,number][]{const m:Record<string,number>={};answers.forEach(a=>{const k=key(a);m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,10)}
function Bars({rows,suffix}:{rows:[string,number][],suffix:string}){const max=Math.max(1,...rows.map(x=>x[1]));return <div className="bars">{rows.length?rows.map(([k,v])=><div className="barRow wide" key={k}><b title={k}>{k}</b><div><i style={{width:`${Math.min(100,v/max*100)}%`}}/></div><span>{v}{suffix}</span></div>):<p className="muted">No data yet.</p>}</div>}
function Trend({answers}:{answers:Answer[]}){const rows=answers.filter(a=>a.date&&a.score10!==null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);return <div className="trend">{rows.map(a=><div className="trendItem" key={a.id} title={`${a.date}: ${a.score10}/10`}><i style={{height:`${Math.max(8,(a.score10||0)/10*100)}%`}}/><small>{a.date.slice(5)}</small></div>)}</div>}
function Calendar(){const answers=useLiveAnswers();const byDate=countBy(answers.filter(a=>a.date),a=>a.date);const active=new Set(byDate.map(x=>x[0]));const today=new Date();const days=Array.from({length:35},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()-34+i);return d.toISOString().slice(0,10)});return <Card title="Last 35 days"><div className="calendarGrid">{days.map(d=><div className={active.has(d)?'day active':'day'} key={d} title={`${d}: ${byDate.find(x=>x[0]===d)?.[1]||0} answers`}>{d.slice(8)}</div>)}</div><p className="muted">{active.size} active days in the displayed window.</p></Card>}
function Revision(){const answers=useLiveAnswers();const gaps=countBy(answers,a=>a.gapCategory||'Unspecified gap').filter(x=>x[0]!=='No gap recorded');const weak=answers.filter(a=>a.score10!==null&&a.score10<5).sort((a,b)=>(a.score10||0)-(b.score10||0));return <div className="grid"><Card title="Priority Revision Gaps">{gaps.length?<Bars rows={gaps}/>:<p className="muted">No recurring gap categories are recorded yet.</p>}</Card><Card title="Lowest Scored Answers"><AnswerList answers={weak} limit={10}/></Card></div>}
function Pyq(){const answers=useLiveAnswers();const pyq=answers.filter(a=>/pyq/i.test(`${a.question} ${a.theme} ${a.subtopic}`));return <Card title={`PYQ-linked answers · ${pyq.length}`}><p className="muted">This tracker now derives from synced answer metadata. A dedicated PYQ dataset can be connected later without changing the answer schema.</p><AnswerList answers={pyq}/></Card>}
function Goals(){const answers=useLiveAnswers();const target=7;const today=new Date().toISOString().slice(0,10);const todayCount=answers.filter(a=>a.date===today).length;return <Card title="Daily Answer Goal"><div className="goal"><strong>{todayCount} / {target}</strong><div className="goalTrack"><i style={{width:`${Math.min(100,todayCount/target*100)}%`}}/></div><p className="muted">Goal is intentionally local UI state until a Goals dataset is connected.</p></div></Card>}
function Learnings(){const answers=useLiveAnswers();const rows=answers.filter(a=>a.learning||a.feedback).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return <Card title="Latest Learnings"><div>{rows.length?rows.map(a=><div className="learning" key={a.id}><b>{a.question||a.subtopic||'Answer'}</b><small>{a.date||'Date unavailable'} · {a.paper}</small><p>{a.learning||a.feedback}</p></div>):<p className="muted">No learning/evaluation text is present in the synced dataset.</p>}</div></Card>}
function Flashcards(){const answers=useLiveAnswers();const cards=answers.filter(a=>a.keywords?.length||a.learning).slice(0,20);return <Card title={`Revision cards · ${cards.length}`}><div className="flashGrid">{cards.map(a=><div className="flash" key={a.id}><small>{a.paper} · {a.subject||a.theme||'General'}</small><b>{a.question||a.subtopic||'Revision point'}</b><p>{a.learning||a.feedback||'No learning text recorded.'}</p></div>)}</div></Card>}
function Settings(){const [c,setC]=useState(getConfig());const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);function update(k:keyof typeof c,v:string|boolean|number){const next={...c,[k]:v};setC(next);saveConfig(next)}async function doSync(){setBusy(true);try{const n=await sync();setMsg(`Successfully synced ${n} answers.`)}catch(e){setMsg(e instanceof Error?e.message:'Sync failed')}finally{setBusy(false)}}return <div className="settings"><Card title="Google Sheet Sync"><p className="muted">Google Sheet remains the source of truth. React uses the same v2 store as the legacy pages.</p><label>Web App URL<input value={c.syncUrl} onChange={e=>update('syncUrl',e.target.value)} placeholder="https://script.google.com/macros/s/.../exec"/></label><label>Sync token<input value={c.syncToken} onChange={e=>update('syncToken',e.target.value)} placeholder="Optional"/></label><label>Auto-sync interval (minutes)<input type="number" min="5" value={c.syncIntervalMinutes} onChange={e=>update('syncIntervalMinutes',Number(e.target.value))}/></label><div className="row"><button onClick={doSync} disabled={busy}>{busy?'Syncing…':'Sync Now'}</button><button className="secondary" onClick={()=>setMsg('Settings saved locally.')}>Save</button></div>{msg&&<p className="notice">{msg}</p>}</Card><Card title="Migration"><p>React + TypeScript is now the active application architecture in <code>/app</code>.</p><p className="muted">Legacy HTML remains available as a fallback while this version is verified.</p></Card></div>}
export default function App(){return <HashRouter><Layout/></HashRouter>}
